nameOverride: ""
fullnameOverride: ""

commonLabels: {}

imagePullSecrets: []

frontend:
  image:
    repository: "hhk7734/wiki-loliot-net"
    tag: "1.0"
    pullPolicy: IfNotPresent

  serviceAccount:
    create: true
    name: ""

  podLabels: {}

  resources: {}

  affinity: {}

  tolerations: []

  service:
    type: ClusterIP
    port: 80

  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage:
