---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wiki.frontend.fullname" . }}
  namespace: {{ include "wiki.namespace" . }}
  labels:
    {{- include "wiki.frontend.labels" . | nindent 4 }}